'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const{runPipeline,getJob,inside,writeGenerated,prepareDesktopApp}=require('../engine');const{configuration}=require('../provider-client');
function temp(){return fs.mkdtempSync(path.join(os.tmpdir(),'of-pipeline-'))}
const meta={id:'11111111-1111-1111-1111-111111111111',name:'Reference',template:'web',mode:'offline',analysis:{features:['Create notes','Search notes','Delete notes']},prompt:'Create offline notes'};
test('reference app completes analysis → generation → compilation → tests → web bundle',async t=>{const dir=temp();t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const r=await runPipeline({projectDir:dir,meta,options:{generator:'reference',referenceFixture:true,target:'web',allowExecution:true}});assert.equal(r.status,'built-requires-review',r.reason);for(const stage of ['analysis','generation','compilation','testing'])assert(r.events.some(e=>e.phase===stage&&e.status==='passed'),stage);assert.equal(r.artifacts.length,1);assert.equal(fs.readFileSync(r.artifacts[0].file).subarray(0,2).toString(),'PK');assert.equal(getJob(dir,r.runId).status,r.status);assert.equal(r.traceability[0].status,'test-passed');});
test('user approval is required before generated command execution',async t=>{const dir=temp();t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const r=await runPipeline({projectDir:dir,meta,options:{generator:'reference',referenceFixture:true,target:'web',allowExecution:false}});assert.equal(r.status,'awaiting-approval');assert.equal(r.artifacts.length,0)});
test('Windows request does not falsely claim release on Linux',async t=>{if(process.platform==='win32')return t.skip('Windows-specific packaging separately covered by CI');const dir=temp();t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const fake=async()=>({ok:true,stdout:'mocked command',stderr:'',exitCode:0});const r=await runPipeline({projectDir:dir,meta,options:{generator:'reference',referenceFixture:true,target:'windows',allowExecution:true,executor:fake}});assert.equal(r.status,'awaiting-windows-runner');assert.equal(r.artifacts.length,0);assert(fs.existsSync(path.join(dir,'files','electron-main.cjs')))});
test('AI compile failure triggers repair and retest',async t=>{const dir=temp();t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));let calls=0;const ai=async()=>{calls++;return calls===1?{model:'test-model',files:{'app.js':'module.exports = {broken: ()=> {','index.html':'<!doctype html><title>Test</title><script src="app.js"></script>','tests/app.test.cjs':"const test=require('node:test');const assert=require('node:assert/strict');test('works',()=>assert.equal(require('../app.js').working(),true));"}}:{model:'test-model',files:{'app.js':'module.exports={working:()=>true};'}}};const r=await runPipeline({projectDir:dir,meta:{...meta,analysis:{features:['Generate working app']}},options:{target:'web',generator:'ai',allowExecution:true},aiGenerate:ai});assert.equal(r.status,'built-requires-review',r.reason);assert.equal(calls,2);assert(r.events.some(e=>e.phase==='automated-repair'&&e.status==='passed'))});
test('generated file paths reject traversal and symlinks',t=>{const dir=temp();t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));assert.throws(()=>inside(dir,'../escape.js'));assert.throws(()=>inside(dir,'/absolute.js'));assert.throws(()=>inside(dir,'dir\\escape.js'));fs.symlinkSync(os.tmpdir(),path.join(dir,'external'));assert.throws(()=>writeGenerated(dir,{'external/escaped.js':'x'}));});
test('desktop wrapper bundles Electron and accepts generic static web projects',t=>{const dir=temp();t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));fs.writeFileSync(path.join(dir,'index.html'),'<h1>Hello</h1>');fs.writeFileSync(path.join(dir,'app.js'),'console.log("hello")');const v=prepareDesktopApp(dir,'Acceptance UI');assert.equal(v.packageJson.build.win.target[0].target,'nsis');assert(!v.packageJson.dependencies);assert.match(fs.readFileSync(path.join(dir,'electron-main.cjs'),'utf8'),/openforge-selftest/);});
test('AI mode selection preserves offline, online and hybrid behavior',()=>{const env={AI_BASE_URL:'https://example.test/v1/chat/completions',AI_MODEL:'cloud',OLLAMA_MODEL:'local'};assert.equal(configuration('offline',env)[0].kind,'ollama');assert.equal(configuration('online',env)[0].kind,'cloud');assert.equal(configuration('hybrid',env).length,2);assert.equal(configuration('offline',{}).length,0)});
