'use strict';
const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { spawn } = require('node:child_process');
const { pipeline } = require('node:stream/promises');
const { createZip } = require('./zip-export');
const {runPipeline,getJob}=require('./pipeline/engine');
const {generate:generatePipelineCode}=require('./pipeline/provider-client');

const ROOT = path.resolve(process.env.OPENFORGE_DATA || path.join(__dirname, 'workspace'));
const PUBLIC = path.join(__dirname, 'public');
const HOST = process.env.HOST || '127.0.0.1';
const PORT = Number(process.env.PORT || 4343);
const TOKEN = process.env.OPENFORGE_TOKEN || '';
const MAX_INPUT = 12 * 1024 * 1024;
const MIME = {'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.json':'application/json; charset=utf-8'};
fs.mkdirSync(ROOT, {recursive:true});

function error(code,message) {const e = new Error(message);e.status=code;throw e;}
function json(res,status,data){const b=JSON.stringify(data);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Content-Length':Buffer.byteLength(b),'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(b);}
function isSubpath(base,target){return target===base || target.startsWith(base+path.sep);}
function safeRel(input){if(typeof input!=='string'||!input||input.includes('\\')||input.includes('\0')||path.isAbsolute(input))error(400,'Invalid relative path');const p=path.posix.normalize(input);if(p==='..'||p.startsWith('../')||p==='.'||p.startsWith('/'))error(400,'Path outside project');return p;}
function projectDir(id){if(!/^[a-f0-9-]{36}$/.test(id||''))error(400,'Invalid project ID');const p=path.join(ROOT,id);if(!fs.existsSync(path.join(p,'project.json')))error(404,'Project not found');return p;}
function projectFile(dir,rel){const p=path.resolve(dir,'files',safeRel(rel));if(!isSubpath(path.join(dir,'files'),p))error(400,'Path escapes project');let current=path.join(dir,'files');for(const part of path.relative(current,p).split(path.sep)){current=path.join(current,part);if(fs.existsSync(current)&&fs.lstatSync(current).isSymbolicLink())error(400,'Symbolic links not allowed');}return p;}
function metadata(dir){return JSON.parse(fs.readFileSync(path.join(dir,'project.json'),'utf8'));}
function persist(dir,obj){fs.writeFileSync(path.join(dir,'project.json'),JSON.stringify(obj,null,2));}
function walk(dir,prefix=''){if(!fs.existsSync(dir))return[];const out=[];for(const e of fs.readdirSync(dir,{withFileTypes:true})){if(e.isSymbolicLink())continue;const rel=path.posix.join(prefix,e.name);if(e.isDirectory())out.push(...walk(path.join(dir,e.name),rel));else if(e.isFile())out.push({path:rel,size:fs.statSync(path.join(dir,e.name)).size});}return out;}
function escaped(s){return String(s).replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&#39;'}[c]));}
function analyze(prompt){let text=String(prompt||'').trim();if(!text)error(400,'Paste a software specification');const lines=text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const features=[];for(const line of lines){if(/^[-*•]\s+|^\d+[.)]\s+|^#{1,5}\s+/.test(line)){const item=line.replace(/^([-*•]|\d+[.)]|#{1,5})\s+/, '').slice(0,280);if(item&&!features.includes(item))features.push(item);}}
if(!features.length)for(const s of text.split(/[.!?]\s+/).filter(x=>x.length>16).slice(0,35))features.push(s.slice(0,280));
const hints=[['Authentication',/login|authentication|register|user access/i],['Database',/database|postgres|sqlite|data model/i],['Reports',/report|pdf|export/i],['Mobile',/android|ios|mobile/i],['Offline',/offline|local model/i],['API',/api|rest|endpoint/i],['Testing',/test|verification|qa/i],['Engineering',/hydraulic|simulation|cfd|engineering/i]];
const tags=hints.filter(([,r])=>r.test(text)).map(([n])=>n);
return {features,tags,characters:text.length,reviewRequired:features.length===0};}
function slug(s){return String(s||'project').normalize('NFKD').toLowerCase().replace(/[^a-z0-9-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,55)||'project';}
function buildFiles(meta){const s=slug(meta.name),title=escaped(meta.name),body=escaped(meta.prompt.slice(0,700));let files={};if(meta.template==='python'){
files={'main.py':`"""${meta.name.replace(/"""/g,'')}: generated starter.\nOriginal prompt retained in REQUIREMENTS.md.\n"""\n\ndef main():\n    print(${JSON.stringify(meta.name+' — running')})\n\nif __name__ == '__main__':\n    main()\n`,'test_main.py':`import unittest\nfrom main import main\n\nclass TestApp(unittest.TestCase):\n    def test_main_exists(self):\n        self.assertTrue(callable(main))\n\nif __name__ == '__main__':\n    unittest.main()\n`};
}else if(meta.template==='api'){
files={'package.json':JSON.stringify({name:s,version:'0.1.0',private:true,scripts:{start:'node server.js',test:'node --test'},engines:{node:'>=20'}},null,2),'server.js':`const http=require('node:http');\nconst server=http.createServer((req,res)=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify({app:${JSON.stringify(meta.name)},status:'ok',path:req.url}));});\nserver.listen(process.env.PORT||5050,()=>console.log('API on '+server.address().port));\n`,'test.js':`const test=require('node:test');const assert=require('node:assert/strict');test('name exists',()=>assert.ok(${JSON.stringify(meta.name)}));\n`};
}else{
files={'index.html':`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><link rel="stylesheet" href="?file=style.css"></head><body><main><p class="eyebrow">GENERATED PROJECT · ${escaped(meta.mode.toUpperCase())}</p><h1>${title}</h1><p class="lead">Editable starter created from your imported specification.</p><section><h2>Imported requirements</h2><div id="requirements"></div></section><section><h2>Project notes</h2><p>${body}</p></section></main><script src="?file=app.js"></script></body></html>`,
'style.css':`*{box-sizing:border-box}body{font-family:system-ui,sans-serif;background:#101b2b;color:#edf3ff;margin:0}main{width:min(900px,92%);margin:8vh auto}.eyebrow{color:#68d8bf;letter-spacing:.1em}h1{font-size:clamp(2.4rem,6vw,4rem)}.lead{color:#b5c4d8}section{background:#1d2c42;padding:26px;border:1px solid #3c5069;border-radius:15px;margin:25px 0}li{margin:12px 0}p{line-height:1.7}`, 
'app.js':`const requirements=${JSON.stringify(meta.analysis.features)};const target=document.getElementById('requirements');const ul=document.createElement('ul');for(const item of requirements){let li=document.createElement('li');li.textContent=item;ul.appendChild(li)}target.appendChild(ul);`};
}
files['REQUIREMENTS.md']=`# ${meta.name}\n\n> Generated starter: additional development is required to implement the full prompt.\n\n## Prompt source\n${meta.source}\n\n## Development mode\n${meta.mode}\n\n## Target platforms\n${meta.platforms.join(', ')}\n\n## Original prompt\n\n${meta.prompt}\n\n## Extracted requirements\n\n${meta.analysis.features.map((x,i)=>`${i+1}. ${x}`).join('\n')}\n`;
files['openforge.manifest.json']=JSON.stringify({name:meta.name,template:meta.template,mode:meta.mode,platforms:meta.platforms,created:meta.created,requirementCount:meta.analysis.features.length,status:'starter-generated',note:'Generated scaffold; full requirements not auto-implemented without configured AI'},null,2);
return files;}
async function readBody(req){let chunks=[],length=0;for await(const c of req){length+=c.length;if(length>MAX_INPUT)error(413,'Request too large');chunks.push(c);}try{return JSON.parse(Buffer.concat(chunks).toString('utf8')||'{}')}catch{error(400,'Invalid JSON');}}
function runProcess(cmd,args,cwd,limitMs=30000){return new Promise(resolve=>{let out='',err='',done=false;const child=spawn(cmd,args,{cwd,env:{...process.env,NO_COLOR:'1',...(process.versions.electron?{ELECTRON_RUN_AS_NODE:'1'}:{})},shell:false,windowsHide:true,stdio:['ignore','pipe','pipe']});const timer=setTimeout(()=>child.kill('SIGKILL'),limitMs);const capture=(which,d)=>{if(which==='out')out=(out+d).slice(-90000);else err=(err+d).slice(-90000)};child.stdout.on('data',d=>capture('out',d.toString()));child.stderr.on('data',d=>capture('err',d.toString()));child.on('error',e=>{if(!done){done=true;clearTimeout(timer);resolve({ok:false,stdout:out,stderr:e.message})}});child.on('close',(code,signal)=>{if(!done){done=true;clearTimeout(timer);resolve({ok:code===0,exitCode:code,signal,stdout:out,stderr:err})}})})}
async function aiGenerate(meta,config){const offline=meta.mode==='offline';let url=offline?(process.env.OLLAMA_URL||'http://127.0.0.1:11434/api/chat'):(process.env.AI_BASE_URL||'');let model=offline?(process.env.OLLAMA_MODEL||'qwen2.5-coder:7b'):(process.env.AI_MODEL||'');if(meta.mode==='hybrid'){const useCloud=!!process.env.AI_BASE_URL;url=useCloud?process.env.AI_BASE_URL:(process.env.OLLAMA_URL||'http://127.0.0.1:11434/api/chat');model=useCloud?(process.env.AI_MODEL||''):(process.env.OLLAMA_MODEL||'qwen2.5-coder:7b');}
if(!url||!model)error(422,'AI provider not configured for this mode. Set AI_BASE_URL + AI_MODEL, or OLLAMA_MODEL and install Ollama.');
const isOllama=url.endsWith('/api/chat');const messages=[{role:'system',content:'You are a coding agent. Return ONLY a JSON object {"files":{"relative/path":"file content"},"notes":"..."}. Generate a working starter implementation for the following specification. Include tests. No markdown fences. Do not create secrets or binary files. Limit output to 10 files and 40KB total. The original requirements remain in REQUIREMENTS.md.'},{role:'user',content:`Project: ${meta.name}\nTarget: ${meta.platforms.join(', ')}\nPrompt:\n${meta.prompt.slice(0,24000)}\nExisting files:\n${JSON.stringify(config.files||{}).slice(0,18000)}`}];
let response;try{response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',...(isOllama?{}:{Authorization:'Bearer '+(process.env.AI_API_KEY||'')})},body:JSON.stringify(isOllama?{model,messages,stream:false,format:'json',options:{num_predict:6000}}:{model,messages,temperature:0.2,response_format:{type:'json_object'}}),signal:AbortSignal.timeout(150000)});}catch(e){error(502,'AI provider unreachable: '+e.message)}if(!response.ok)error(502,'AI provider returned '+response.status+': '+(await response.text()).slice(0,700));let result=await response.json();let raw=isOllama?result.message?.content:result.choices?.[0]?.message?.content;if(!raw)error(502,'AI provider returned no content');raw=raw.replace(/^```(?:json)?\s*|\s*```$/g,'').trim();let obj;try{obj=JSON.parse(raw)}catch{error(502,'AI returned invalid JSON; retry with a stronger code model')};if(typeof obj.files!=='object'||!obj.files||Array.isArray(obj.files))error(502,'AI response missing files object');const entries=Object.entries(obj.files);if(entries.length>30)error(422,'AI output contains too many files in one generation batch');let total=0;for(const [key,value] of entries){safeRel(key);if(typeof value!=='string')error(422,'Non-text file returned');total+=value.length;}if(total>500000)error(422,'AI output exceeds per-batch limit');return {files:obj.files,notes:obj.notes||'',model};}
function ensurePrivate(req){if(HOST!=='127.0.0.1'&&HOST!=='localhost'&&!TOKEN)error(503,'Set OPENFORGE_TOKEN when exposing server beyond loopback');if(TOKEN){const supplied=req.headers['x-openforge-token']||String(req.headers.authorization||'').replace(/^Bearer /,'');if(supplied!==TOKEN)error(401,'Authentication required');}}
async function handle(req,res){try{const url=new URL(req.url,'http://localhost');const p=url.pathname;if(p.startsWith('/api/')){ensurePrivate(req);const route=p.split('/').filter(Boolean),method=req.method;
if(method==='GET'&&p==='/api/health')return json(res,200,{ok:true,version:'0.6.0',mode:'offline-first',root:ROOT,capabilities:{scaffold:true,localEditing:true,requirements:true,ai:!!process.env.AI_BASE_URL||!!process.env.OLLAMA_MODEL,builds:true,pipeline:true,windowsPackagingRequiresWindows:true,theiaProductSourceBundled:true}});
if(method==='GET'&&p==='/api/projects'){const list=fs.readdirSync(ROOT,{withFileTypes:true}).filter(x=>x.isDirectory()&&fs.existsSync(path.join(ROOT,x.name,'project.json'))).map(x=>metadata(path.join(ROOT,x.name)));return json(res,200,{projects:list.sort((a,b)=>b.created.localeCompare(a.created))});}
if(method==='POST'&&p==='/api/analyze'){const b=await readBody(req);return json(res,200,analyze(b.prompt));}
if(method==='POST'&&p==='/api/projects'){const b=await readBody(req);if(!String(b.name||'').trim())error(400,'Project name required');const prompt=String(b.prompt||'').trim();const a=analyze(prompt),mode=['online','offline','hybrid'].includes(b.mode)?b.mode:'hybrid',template=['web','python','api'].includes(b.template)?b.template:'web';const platforms=Array.isArray(b.platforms)?b.platforms.filter(x=>['Windows','Linux','macOS','Web','Android','iOS'].includes(x)):['Web'];let id=crypto.randomUUID(),dir=path.join(ROOT,id);const meta={id,name:String(b.name).slice(0,100),source:String(b.source||'Other AI').slice(0,80),mode,template,platforms,prompt,analysis:a,created:new Date().toISOString(),updated:new Date().toISOString(),status:'starter-generated',history:[]};fs.mkdirSync(path.join(dir,'files'),{recursive:true});for(const [file,content]of Object.entries(buildFiles(meta))){const dest=projectFile(dir,file);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,content);}persist(dir,meta);return json(res,201,{project:meta,files:walk(path.join(dir,'files'))});}
if(method==='POST'&&p==='/api/acceptance/sample'){const b=await readBody(req);const id=crypto.randomUUID(),dir=path.join(ROOT,id);const prompt='# Offline notes application\n- Create notes and save them locally\n- Search saved notes\n- Delete notes\n- Install on clean Windows without external Node or Yarn';const meta={id,name:'OpenForge Notes',source:'OpenForge acceptance fixture',mode:'offline',template:'web',platforms:['Windows','Web'],prompt,analysis:analyze(prompt),created:new Date().toISOString(),updated:new Date().toISOString(),status:'acceptance-fixture',acceptanceFixture:true,history:[]};fs.mkdirSync(path.join(dir,'files'),{recursive:true});persist(dir,meta);return json(res,201,{project:meta});}
    if(route[0]==='api'&&route[1]==='projects'&&route[2]){const id=route[2],dir=projectDir(id),meta=metadata(dir);
if(method==='GET'&&route.length===3)return json(res,200,{project:meta,files:walk(path.join(dir,'files'))});
if(method==='PATCH'&&route.length===3){const b=await readBody(req);if(b.mode&&!['online','offline','hybrid'].includes(b.mode))error(400,'Invalid mode');if(b.mode)meta.mode=b.mode;meta.updated=new Date().toISOString();persist(dir,meta);return json(res,200,{project:meta});}
if(method==='POST'&&route[3]==='pipeline'&&route.length===4){const b=await readBody(req);if(b.generator==='reference'&&!meta.acceptanceFixture)error(403,'Only designated acceptance projects may use the reference generator');if(b.generator&& !['ai','reference'].includes(b.generator))error(400,'Invalid generator');if(b.target&&!['windows','web'].includes(b.target))error(400,'This release supports Windows and Web packaging');if(b.approveExecution&&HOST!=='127.0.0.1'&&HOST!=='localhost')error(403,'Automated execution must run on a trusted local or isolated worker');let started;const work=runPipeline({projectDir:dir,meta,options:{generator:b.generator||'ai',referenceFixture:!!meta.acceptanceFixture,target:b.target||'windows',allowExecution:b.approveExecution===true,maxRepairs:Math.min(3,Math.max(0,Number(b.maxRepairs??2))),onCreated:job=>{started=job;}},aiGenerate:generatePipelineCode});work.catch(e=>console.error('Pipeline failed:',e));return json(res,202,{run:started,link:'/api/projects/'+id+'/pipeline/'+started.runId});}
    if(method==='GET'&&route[3]==='pipeline'&&route[4]&&route.length===5){try{return json(res,200,{run:getJob(dir,route[4])})}catch(e){error(404,e.message)}}
    if(method==='GET'&&route[3]==='pipeline'&&route[4]&&route[5]==='artifact'){let job;try{job=getJob(dir,route[4])}catch(e){error(404,e.message)}const artifact=job.artifacts?.[Number(url.searchParams.get('index')||0)];if(!artifact||!fs.existsSync(artifact.file))error(404,'Artifact not found');const allow=[path.join(dir,'files','dist'),path.join(dir,'.openforge-runs',route[4])];const full=path.resolve(artifact.file);if(!allow.some(base=>isSubpath(base,full)))error(403,'Artifact path outside project');res.writeHead(200,{'Content-Type':artifact.type==='windows-nsis-installer'?'application/vnd.microsoft.portable-executable':'application/zip','Content-Disposition':'attachment; filename="'+path.basename(full)+'"','Content-Length':fs.statSync(full).size});return fs.createReadStream(full).pipe(res);}
    if(method==='GET'&&route[3]==='file'){const file=projectFile(dir,url.searchParams.get('path'));if(!fs.existsSync(file)||!fs.statSync(file).isFile())error(404,'File not found');const stat=fs.statSync(file);if(stat.size>2e6)error(413,'File too large for editor');return json(res,200,{path:url.searchParams.get('path'),content:fs.readFileSync(file,'utf8')});}
if(method==='PUT'&&route[3]==='file'){const b=await readBody(req);if(typeof b.content!=='string'||b.content.length>2e6)error(400,'Invalid file content');const rel=safeRel(b.path),file=projectFile(dir,rel);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,b.content,'utf8');meta.updated=new Date().toISOString();meta.history.push({time:meta.updated,action:'saved',path:rel});meta.history=meta.history.slice(-200);persist(dir,meta);return json(res,200,{ok:true,path:rel});}
if(method==='POST'&&route[3]==='ai'){const b=await readBody(req),result=await aiGenerate(meta,b);const proposalId=crypto.randomUUID();fs.writeFileSync(path.join(dir,`proposal-${proposalId}.json`),JSON.stringify({...result,created:new Date().toISOString()}));return json(res,200,{proposalId,...result,requiresApproval:true});}
if(method==='POST'&&route[3]==='apply'){const b=await readBody(req);if(!/^[a-f0-9-]{36}$/.test(b.proposalId||''))error(400,'Invalid proposal ID');const file=path.join(dir,`proposal-${b.proposalId}.json`);if(!fs.existsSync(file))error(404,'Proposal missing');const proposal=JSON.parse(fs.readFileSync(file,'utf8'));const changed=[];for(const [rel,data] of Object.entries(proposal.files)){const dest=projectFile(dir,rel);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,data);changed.push(rel)}fs.unlinkSync(file);meta.updated=new Date().toISOString();meta.status='AI changes applied — unverified';meta.history.push({time:meta.updated,action:'AI proposal applied',files:changed});persist(dir,meta);return json(res,200,{ok:true,changed});}
if(method==='POST'&&route[3]==='test'){const f=path.join(dir,'files'),kind=meta.template;const runner=kind==='python'?['python',['-m','unittest','discover','-v']]:kind==='api'?[process.execPath,['--test','test.js']]:[process.execPath,['--check','app.js']];const result=await runProcess(runner[0],runner[1],f);return json(res,200,{command:runner.join(' '),...result,note:kind==='web'?'Syntax check only, not browser E2E validation':'Starter test command'});}
if(method==='POST'&&route[3]==='git'){const f=path.join(dir,'files');let result=await runProcess('git',['init'],f);if(!result.ok)return json(res,500,result);await runProcess('git',['add','.'],f);result=await runProcess('git',['-c','user.name=OpenForge','-c','user.email=openforge@localhost','commit','-m','Initial OpenForge project'],f);return json(res,200,result);}
if(method==='GET'&&route[3]==='export'){const f=path.join(dir,'files');res.writeHead(200,{'Content-Type':'application/zip','Content-Disposition':`attachment; filename="${slug(meta.name)}.zip"`,'Cache-Control':'no-store'});createZip(f,res);return;}
if(method==='GET'&&route[3]==='preview'){const requested=url.searchParams.get('file')||route[4]||'index.html';if(meta.template!=='web')error(400,'Preview only supported for web template');if(!['index.html','style.css','app.js','notes.js'].includes(requested))error(400,'Preview only supports starter files');const f=projectFile(dir,requested);if(!fs.existsSync(f))error(404,'Preview file missing');const data=fs.readFileSync(f);res.writeHead(200,{'Content-Type':MIME[path.extname(f)]||'text/plain','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self'",'X-Content-Type-Options':'nosniff'});return res.end(data);}
}
return error(404,'Unknown API route');}
if(req.method!=='GET')error(405,'Method not allowed');if(p==='/config.js'){res.writeHead(200,{'Content-Type':'application/javascript','Cache-Control':'no-store'});return res.end(`window.OPENFORGE_AUTH_REQUIRED=${JSON.stringify(!!TOKEN)};`)}
let file=path.resolve(PUBLIC,'.'+(p==='/'?'/index.html':p));if(!isSubpath(PUBLIC,file)||!fs.existsSync(file)||fs.statSync(file).isDirectory())error(404,'File not found');res.writeHead(200,{'Content-Type':MIME[path.extname(file)]||'application/octet-stream','Content-Security-Policy':"default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; frame-src 'self'",'X-Content-Type-Options':'nosniff'});return fs.createReadStream(file).pipe(res);
}catch(e){if(!res.headersSent)json(res,e.status||500,{error:e.status?e.message:'Internal error: '+e.message});else res.end();}}
if(require.main===module){http.createServer(handle).listen(PORT,HOST,()=>console.log(`OpenForge AI Studio available at http://${HOST}:${PORT}`));}
module.exports={handle,analyze,safeRel,buildFiles,ROOT};
